name: Android CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570"
    - name: Build with Gradle
      run: ./gradlew build --debug --warning-mode all

  test-unit:
    name: Run Unit Tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570"
    - name: Execute unit tests
      run: ./gradlew test --stacktrace
  
  test-instrumentation:
    name: Run Instrumentation Tests

    runs-on: macOS-latest

    strategy:
      matrix:
        api-level: [23, 28]
        target: [default, google_apis]
    steps:
    - uses: actions/checkout@v1
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Execute instrumentation tests
      uses: reactivecircus/android-emulator-runner@v2.4.0
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        script: ./gradlew connectedCheck
